name: Release Plugin

on:
  push:
    branches: [main, beta]
    paths:
      - 'packages/plugin/**/*'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn workspaces focus @chainsafe/cypress-polkadot-wallet
      - name: Build
        run: yarn plugin:build
      - name: Release
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release
